### ISSUE TITLE
Forbrug helt skævt

### ISSUE THREAD

**Issue by handswork** [torben87/DitElforbrugExcelPriser#1]
Har udfordringer med at få tallene til at stemme
2022 ser ud til at blive fordoblet i forhold til virkeligheden. Samme for 2018-20
2021 er helt væk, påstår at vi har købt for knap 200.000,- el (hvilket jeg ikke håber den har ret i ;-) )

**Comment by torben87** [comment]
Haha, nej det håber jeg virkelig ikke er dit reelle forbrug :D Jeg har rettet i koden, så den nu gerne skulle kunne håndtere din udbyder også (der er lidt forskel på hvordan de melder deres tariffer ind, kan jeg se).
